In [2]:
import pandas as pd
import numpy as np

In [3]:
data = pd.read_csv('data.csv')

In [19]:
data

,Student Code,Degree,Student Name,Mid,Quiz 1,Quiz 2,Best of Quizzes,Assignment 1,Assignment 2,Best of Assignments,Total Sessional (50),Final (50),Total (100),Grade
0,022-14-19987,BS(CS),Abdul Basit,28,8.0,3.0,8,7.0,9.0,9,45,25.0,70,B
1,022-14-110233,BS(CS),Adeel Ahmed,17,NaN,5.0,5,8.0,10.0,10,32,18.0,50,F
2,022-14-110585,BS(CS),Afrah Zareen,18,5.0,2.0,5,8.0,10.0,10,33,30.0,63,C
3,022-14-19718,BS(CS),Ahmed Ali Raza,14,7.0,2.0,7,NaN,2.0,2,23,23.0,46,F
4,022-14-110648,BS(CS),Ahsan Ali Vohra,27,7.0,6.0,7,7.0,9.0,9,43,34.0,77,B
5,022-14-110232,BS(CS),Ameer Hamza,25,9.0,6.0,9,8.0,10.0,10,44,27.0,71,B
6,022-14-110588,BS(CS),Anas Ali Khan,28,5.0,6.0,6,8.0,10.0,10,44,30.0,74,B
7,022-14-110388,BS(CS),Aneebullah Niazi,26,9.0,6.0,9,8.0,10.0,10,45,40.0,85,A
8,022-14-110601,BS(CS),Areesha Sohail,19,9.0,4.0,9,7.0,9.0,9,37,24.0,61,C
9,022-14-110599,BS(CS),Arsalan,28,8.0,6.0,8,8.0,NaN,8,44,40.0,84,A
10,022-14-110214,BS(CS),Fatima Haider Warsi,30,8.0,7.0,8,8.0,NaN,8,46,45.0,91,A
11,022-14-110591,BS(CS),Habib Ullah,28,8.0,5.0,8,5.0,NaN,5,41,35.0,76,B
12,022-15-110994,BS(CS),Hafiza Tooba Akbani,23,7.0,5.0,7,8.0,10.0,10,40,33.0,73,B
13,022-14-110600,BS(CS),Hamza Abdul Jabbar,24,8.0,4.0,8,8.0,10.0,10,42,25.0,67,C
14,022-14-110389,BS(CS),Hareem Afshan,21,7.0,4.0,7,6.0,8.0,8,36,29.0,65,C
15,022-14-19916,BS(CS),Haseeb Sajid,18,NaN,NaN,0,NaN,NaN,0,18,NaN,18,F
16,022-14-110596,BS(CS),Hassam Ahmed,23,5.0,5.0,5,7.0,9.0,9,37,35.0,72,B
17,022-14-110396,BS(CS),Khalid Anwer,20,8.0,5.0,8,9.0,11.0,11,39,31.0,70,B
18,022-14-110223,BS(CS),Madiha Jabeen,16,5.0,2.0,5,8.0,10.0,10,31,29.0,60,C
19,022-14-110222,BS(CS),Mohammad Hunain,27,9.0,6.0,9,8.0,10.0,10,46,45.0,91,A
20,022-14-110412,BS(CS),Muhammad Aamir,24,7.0,6.0,7,7.0,9.0,9,40,31.0,71,B
21,022-14-110593,BS(CS),Muhammad Abdul Rehman Siddiqui,20,9.0,6.0,9,9.0,11.0,11,40,20.0,60,C
22,022-14-110398,BS(CS),Muhammad Abdullah,20,7.0,6.0,7,7.0,NaN,7,34,23.0,57,F
23,022-14-19983,BS(CS),Muhammad Ali Iqbal,26,5.0,NaN,5,8.0,10.0,10,41,21.0,62,C
24,022-14-110215,BS(CS),Muhammad Bilal,28,5.0,4.0,5,9.0,11.0,11,44,33.0,77,B
25,022-14-110105,BS(CS),Muhammad Faraz,26,9.0,6.0,9,8.0,10.0,10,45,41.0,86,A
26,022-14-110370,BS(CS),Muhammad Ghazali Faridi,27,6.0,NaN,6,6.0,8.0,8,41,24.0,65,C
27,022-14-110452,BS(CS),Muhammad Osama Khan,27,8.0,6.0,8,8.0,10.0,10,45,26.0,71,B
28,022-14-110387,BS(CS),Muhammad Saqib Intizar,22,6.0,6.0,6,9.0,11.0,11,39,18.0,57,F
29,022-14-110217,BS(CS),Muhammad Shahroz Khurshid,17,7.0,1.0,7,6.0,NaN,6,30,9.0,39,F
30,022-14-110401,BS(CS),Muhammad Shozab,23,8.0,6.0,8,9.0,NaN,9,40,32.0,72,B
31,022-14-110231,BS(CS),Muhammad Taha Hasnain,27,7.0,5.0,7,10.0,NaN,10,44,29.0,73,B
32,022-14-110035,BS(CS),Muhammad Wajahat Khan,9,NaN,2.0,2,8.0,10.0,10,21,8.0,29,F
33,022-14-19919,BS(CS),Muhammad Younus Baig,20,4.0,2.0,4,8.0,10.0,10,34,17.0,51,F
34,022-14-110413,BS(CS),Nazeer Bin Zafar,25,9.0,6.0,9,8.0,10.0,10,44,42.0,86,A
35,022-14-19923,BS(CS),Rabi Ahmed,20,8.0,5.0,8,NaN,10.0,10,38,28.0,66,C
36,022-14-110582,BS(CS),Rida Nasim,25,9.0,5.0,9,9.0,NaN,9,43,27.0,70,B
37,022-14-110230,BS(CS),Sadaf Nosheen,27,9.0,5.0,9,9.0,NaN,9,45,30.0,75,B
38,022-14-110229,BS(CS),Sadaquat Rafique,9,6.0,6.0,6,5.0,7.0,7,22,17.0,39,F
39,022-14-110107,BS(CS),Sania Iqbal,28,4.0,4.0,4,9.0,11.0,11,43,25.0,68,C
40,022-14-110584,BS(CS),Sharif Taqi,27,9.0,6.0,9,8.0,10.0,10,46,35.0,81,A
41,022-14-110225,BS(CS),Shariqa Ahmad,20,7.0,6.0,7,8.0,10.0,10,37,20.0,57,F
42,022-14-110587,BS(CS),Sumbul Rehman,28,5.0,6.0,6,8.0,10.0,10,44,23.0,67,C
43,022-14-110451,BS(CS),Syed Faizan Uddin,28,9.0,4.0,9,6.0,8.0,8,45,34.0,79,B
44,022-14-110589,BS(CS),Syed Sohaib,25,7.0,5.0,7,9.0,NaN,9,41,22.0,63,C
45,022-14-110400,BS(CS),Syeda Sabika Raza,27,9.0,6.0,9,9.0,NaN,9,45,35.0,80,A
46,022-14-19911,BS(CS),Usman Khan,25,8.0,5.0,8,8.0,10.0,10,43,22.0,65,C
47,022-14-110219,BS(CS),Waqar Ahmed,11,9.0,5.0,9,5.0,7.0,7,27,19.0,46,F

In [112]:
data[(data["Assignment 1"] >= 7) ].count()

Student Code            6
Degree                  6
Student Name            6
Mid                     6
Quiz 1                  6
Quiz 2                  6
Best of Quizzes         6
Assignment 1            6
Assignment 2            5
Best of Assignments     6
Total Sessional (50)    6
Final (50)              6
Total (100)             6
Grade                   6
dtype: int64

In [45]:
names=data[(data["Assignment 1"]>=7)& (data["Assignment 2"]>=7)]["Student Name"]
names

0                        Abdul Basit
1                        Adeel Ahmed
2                       Afrah Zareen
4                    Ahsan Ali Vohra
5                        Ameer Hamza
6                      Anas Ali Khan
7                   Aneebullah Niazi
8                     Areesha Sohail
12               Hafiza Tooba Akbani
13                Hamza Abdul Jabbar
16                      Hassam Ahmed
17                      Khalid Anwer
18                     Madiha Jabeen
19                   Mohammad Hunain
20                    Muhammad Aamir
21    Muhammad Abdul Rehman Siddiqui
23                Muhammad Ali Iqbal
24                    Muhammad Bilal
25                    Muhammad Faraz
27               Muhammad Osama Khan
28            Muhammad Saqib Intizar
32             Muhammad Wajahat Khan
33              Muhammad Younus Baig
34                  Nazeer Bin Zafar
39                       Sania Iqbal
40                       Sharif Taqi
41                     Shariqa Ahmad
42                     Sumbul Rehman
46                        Usman Khan
Name: Student Name, dtype: object

In [47]:
for i in names:
    i=str(i)
    if i.startswith("Muhammad") or i.startswith("Mohammad"):
        print(i)

Mohammad Hunain
Muhammad Aamir
Muhammad Abdul Rehman Siddiqui
Muhammad Ali Iqbal
Muhammad Bilal
Muhammad Faraz
Muhammad Osama Khan
Muhammad Saqib Intizar
Muhammad Wajahat Khan
Muhammad Younus Baig

In [51]:
x =  pd.Series(range(6), index=['a','b','c','d','1','A'])

In [109]:
y = pd.DataFrame(range(4,2),  index=["one", "two"], columns= ["a","b","c","d"])
y.loc["one"]=[1,9,6,7]
y.loc["two"]=[8,4,16,13]
y

     a  b   c   d
one  1  9   6   7
two  8  4  16  13

In [111]:
y.sort_index(axis=0, ascending=False, inplace=True)
y

     a  b   c   d
two  8  4  16  13
one  1  9   6   7

In [118]:
data[data["Assignment 1"].isin([8,9])]   #retrieve data on the specific values of coloumn for entire dataFrame

,Student Code,Degree,Student Name,Mid,Quiz 1,Quiz 2,Best of Quizzes,Assignment 1,Assignment 2,Best of Assignments,Total Sessional (50),Final (50),Total (100),Grade
1,022-14-110233,BS(CS),Adeel Ahmed,17,NaN,5.0,5,8.0,10.0,10,32,18.0,50,F
2,022-14-110585,BS(CS),Afrah Zareen,18,5.0,2.0,5,8.0,10.0,10,33,30.0,63,C
5,022-14-110232,BS(CS),Ameer Hamza,25,9.0,6.0,9,8.0,10.0,10,44,27.0,71,B
6,022-14-110588,BS(CS),Anas Ali Khan,28,5.0,6.0,6,8.0,10.0,10,44,30.0,74,B
7,022-14-110388,BS(CS),Aneebullah Niazi,26,9.0,6.0,9,8.0,10.0,10,45,40.0,85,A
9,022-14-110599,BS(CS),Arsalan,28,8.0,6.0,8,8.0,NaN,8,44,40.0,84,A
10,022-14-110214,BS(CS),Fatima Haider Warsi,30,8.0,7.0,8,8.0,NaN,8,46,45.0,91,A
12,022-15-110994,BS(CS),Hafiza Tooba Akbani,23,7.0,5.0,7,8.0,10.0,10,40,33.0,73,B
13,022-14-110600,BS(CS),Hamza Abdul Jabbar,24,8.0,4.0,8,8.0,10.0,10,42,25.0,67,C
17,022-14-110396,BS(CS),Khalid Anwer,20,8.0,5.0,8,9.0,11.0,11,39,31.0,70,B
18,022-14-110223,BS(CS),Madiha Jabeen,16,5.0,2.0,5,8.0,10.0,10,31,29.0,60,C
19,022-14-110222,BS(CS),Mohammad Hunain,27,9.0,6.0,9,8.0,10.0,10,46,45.0,91,A
21,022-14-110593,BS(CS),Muhammad Abdul Rehman Siddiqui,20,9.0,6.0,9,9.0,11.0,11,40,20.0,60,C
23,022-14-19983,BS(CS),Muhammad Ali Iqbal,26,5.0,NaN,5,8.0,10.0,10,41,21.0,62,C
24,022-14-110215,BS(CS),Muhammad Bilal,28,5.0,4.0,5,9.0,11.0,11,44,33.0,77,B
25,022-14-110105,BS(CS),Muhammad Faraz,26,9.0,6.0,9,8.0,10.0,10,45,41.0,86,A
27,022-14-110452,BS(CS),Muhammad Osama Khan,27,8.0,6.0,8,8.0,10.0,10,45,26.0,71,B
28,022-14-110387,BS(CS),Muhammad Saqib Intizar,22,6.0,6.0,6,9.0,11.0,11,39,18.0,57,F
30,022-14-110401,BS(CS),Muhammad Shozab,23,8.0,6.0,8,9.0,NaN,9,40,32.0,72,B
32,022-14-110035,BS(CS),Muhammad Wajahat Khan,9,NaN,2.0,2,8.0,10.0,10,21,8.0,29,F
33,022-14-19919,BS(CS),Muhammad Younus Baig,20,4.0,2.0,4,8.0,10.0,10,34,17.0,51,F
34,022-14-110413,BS(CS),Nazeer Bin Zafar,25,9.0,6.0,9,8.0,10.0,10,44,42.0,86,A
36,022-14-110582,BS(CS),Rida Nasim,25,9.0,5.0,9,9.0,NaN,9,43,27.0,70,B
37,022-14-110230,BS(CS),Sadaf Nosheen,27,9.0,5.0,9,9.0,NaN,9,45,30.0,75,B
39,022-14-110107,BS(CS),Sania Iqbal,28,4.0,4.0,4,9.0,11.0,11,43,25.0,68,C
40,022-14-110584,BS(CS),Sharif Taqi,27,9.0,6.0,9,8.0,10.0,10,46,35.0,81,A
41,022-14-110225,BS(CS),Shariqa Ahmad,20,7.0,6.0,7,8.0,10.0,10,37,20.0,57,F
42,022-14-110587,BS(CS),Sumbul Rehman,28,5.0,6.0,6,8.0,10.0,10,44,23.0,67,C
44,022-14-110589,BS(CS),Syed Sohaib,25,7.0,5.0,7,9.0,NaN,9,41,22.0,63,C
45,022-14-110400,BS(CS),Syeda Sabika Raza,27,9.0,6.0,9,9.0,NaN,9,45,35.0,80,A
46,022-14-19911,BS(CS),Usman Khan,25,8.0,5.0,8,8.0,10.0,10,43,22.0,65,C